<?xml version="1.0"?>

<robot name="limo_four_diff" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:arg name="robot_name" default="limo_four_diff"/>
  <xacro:arg name="namespace" default=""/>

  <xacro:include filename="$(find limo_simulation)/model/limo_xacro.xacro" />
  <xacro:include filename="$(find limo_simulation)/model/limo_four_diff.gazebo" ns='$(arg namespace)'/> 

  <!-- Variables -->
  <xacro:property name="M_PI" value="3.14159"/>

  <!-- Vehicle Geometries -->
  <xacro:property name="base_x_size" value="0.13" />
  <xacro:property name="base_y_size" value="0.12" />
  <xacro:property name="base_z_size" value="0.1" />

  <xacro:property name="wheelbase" value="0.2"/>
  <xacro:property name="track" value="0.13"/>
  <xacro:property name="wheel_vertical_offset" value="-0.10" />
  <xacro:property name="base_mass" value="2.1557"/>

  <xacro:property name="wheel_length" value="0.045" />
  <xacro:property name="wheel_radius" value="0.045" />
  <link name="$(arg robot_name)/base_footprint"/>

  <joint name="$(arg robot_name)/base_joint" type="fixed">
    <parent link="$(arg robot_name)/base_footprint"/>
    <child link="$(arg robot_name)/base_link"/>
    <origin xyz="0.0 0.0 0.15" rpy="0 0 0"/>
  </joint>
    <!-- Base link -->
    <link name="$(arg robot_name)/base_link">
        <visual>
            <origin xyz="0 0 -0.15" rpy="0 0 1.57" />
            <geometry>
                <mesh filename="file://$(find limo_simulation)/meshes/limo_base.dae" scale="1 1 1"/>
            </geometry>
        </visual>
        <collision>
            <!--origin xyz="0 0 -0.15" rpy="0 0 1.57" /-->
            <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
              <box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
          </geometry>
        </collision>
    </link>

    <link name="$(arg robot_name)/inertial_link">
        <inertial>
            <origin xyz="0.0 0.0 0.0" />
            <mass value="${base_mass}" />
            <inertia ixx="0.24" ixy="0" ixz="0" 
                     iyy="0.96" iyz="0" 
                     izz="0.96" />
        </inertial>
    </link>

    <joint name="inertial_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="$(arg robot_name)/base_link" />
        <child link="$(arg robot_name)/inertial_link" />
    </joint>

    <xacro:limo_laser parent_prefix="$(arg robot_name)/base_link" frame_prefix="$(arg robot_name)/laser">
        <origin xyz="0.103 0 -0.034" rpy="0 0 0"/>
    </xacro:limo_laser>

    <xacro:limo_depth_camera parent_prefix="$(arg robot_name)/base_link" frame_prefix="$(arg robot_name)/depth_camera">
        <origin xyz="0.084 0 0.3" rpy="0 0 0"/>
    </xacro:limo_depth_camera>
    
    <xacro:limo_imu parent_prefix="$(arg robot_name)/base_link" frame_prefix="$(arg robot_name)/imu">
        <origin xyz="0.0 0 -0.1" rpy="0 0 0"/>
    </xacro:limo_imu>

    <xacro:limo_wheel parent_prefix="$(arg robot_name)/base_link" wheel_prefix="front_left" reflect="1">
        <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0  0" />
    </xacro:limo_wheel>

    <xacro:limo_wheel parent_prefix="$(arg robot_name)/base_link" wheel_prefix="front_right" reflect="-1">
        <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="${M_PI} 0 0" />
    </xacro:limo_wheel>

    <xacro:limo_wheel parent_prefix="$(arg robot_name)/base_link" wheel_prefix="rear_left" reflect="1">
        <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:limo_wheel>

    <xacro:limo_wheel parent_prefix="$(arg robot_name)/base_link" wheel_prefix="rear_right" reflect="-1">
        <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="${M_PI} 0 0" />
    </xacro:limo_wheel>
  

    <gazebo reference="imu_link">
    <gravity>true</gravity>
    <sensor name="twr_imu" type="imu">
      <always_on>true</always_on>
      <update_rate>100</update_rate>
      <visualize>true</visualize>
      <imu>
        <orientation>
          <x>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>2e-3</stddev>
            </noise>
          </x>
          <y>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>2e-3</stddev>
            </noise>
          </y>
          <z>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>2e-3</stddev>
            </noise>
          </z>
        </orientation>
        <angular_velocity>
          <x>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>2e-4</stddev>
            </noise>
          </x>
          <y>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>2e-4</stddev>
            </noise>
          </y>
          <z>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>2e-4</stddev>
            </noise>
          </z>
        </angular_velocity>
        <linear_acceleration>
          <x>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>1.7e-2</stddev>
            </noise>
          </x>
          <y>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>1.7e-2</stddev>
            </noise>
          </y>
          <z>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>1.7e-2</stddev>
            </noise>
          </z>
        </linear_acceleration>
      </imu>
      <plugin name="$(arg robot_name)_two_wheeled_robot_imu" filename="libgazebo_ros_imu_sensor.so">
        <initial_orientation_as_reference>false</initial_orientation_as_reference>
        <frame_name>imu_link</frame_name>
        <ros>
          <namespace>/imu</namespace>
          <remapping>~/out:=data</remapping>
        </ros>
      </plugin>
    </sensor>
</gazebo>

<gazebo reference="$(arg robot_name)/laser_link">
    <sensor name="$(arg robot_name)/laser" type="ray">
      <always_on>true</always_on>
      <visualize>false</visualize>
      <update_rate>8</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>720</samples>
            <resolution>1.000000</resolution>
            <min_angle>-2.09439504</min_angle>
            <max_angle>2.09439504</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.3</min>
          <max>8.0</max>
          <resolution>0.015</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="scan" filename="libgazebo_ros_ray_sensor.so">
        <ros>
          <namespace>$(arg robot_name)</namespace>
          <remapping>~/out:=scan</remapping>
        </ros>
        <output_type>sensor_msgs/LaserScan</output_type>
        <frame_name>$(arg robot_name)/laser_link</frame_name>
      </plugin>
    </sensor>
  </gazebo>
</robot>
